import { Migration } from "@medusajs/framework/mikro-orm/migrations";

/**
 * Say what a deferred row is waiting for.
 *
 * Generated by `medusa plugin:db:generate`; the SQL below is untouched.
 * Nullable, no default, no backfill - existing rows stay null, which reads as
 * "not waiting on data", the same thing every row said before this column
 * existed.
 */
export class Migration20260902131444 extends Migration {

  override async up(): Promise<void> {
    this.addSql(`alter table if exists "infakt_invoice" add column if not exists "defer_reason" text null;`);
  }

  override async down(): Promise<void> {
    this.addSql(`alter table if exists "infakt_invoice" drop column if exists "defer_reason";`);
  }

}
